# REFACTOR: ????? ??????? ? ?????????? ?????????
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.enabled=true

server.port=8080

# REFACTOR: ddl-auto=validate (?? none, ?? drop-first)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/shelter_tg_bot_evs_bodn_DB
spring.datasource.username=evgenyevs_bodnevich
spring.datasource.password=tg123

spring.liquibase.clear-checksums=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.drop-first=true

logging.level.liquibase=DEBUG