spring.datasource.url=jdbc:postgresql://localhost:5432/shelter_tg_bot_evs_bodn_DB
spring.datasource.username=evgenyevs_bodnevich
spring.datasource.password=tg123
telegram.bot.token=8631759152:AAGv15uhV-pOtpr0rTDb6WEjX7Bv_sm8Fsc
server.port=8080
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.clear-checksums=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
spring.liquibase.drop-first=true
logging.level.liquibase=DEBUG
